### PR TITLE
chore: workaround vite package build error

### PR DESCRIPTION
**Pull request by hi-ogawa**
### Description

In addition to https://github.com/rolldown/rolldown/pull/1642, it looks like `replaceConfusingTypeNames` is messing with vite package build. I haven't checked the error in a detail, but maybe it's okay to skip it for starter?

I temporary included a patch for `binding.d.ts` type error in the PR to verify `pnpm build` succeeds.

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
The latest rolldown would be `0.12.1`

**Comment by hi-ogawa** [comment]
Thanks for the heads up! I'll test that with 0.12.1

**Comment by hi-ogawa** [comment]
Starting to check tests failure. Let me put some notes here

<details><summary>playground/external</summary>

## before

```ts
// -------- node_modules/.vite/deps/@vitejs_test-dep-that-requires.js?v=7ce498d7
import {
  require_vue
} from "/node_modules/.vite/deps/chunk-ACQTEB6D.js?v=d821959b";
import {
  require_slash
} from "/node_modules/.vite/deps/chunk-PNJKIXPP.js?v=d821959b";

// ../../node_modules/.pnpm/@vitejs+test-dep-that-requires@file+playground+external+dep-that-requires_typescript@5.2.2/node_modules/@vitejs/test-dep-that-requires/index.js
var { version } = require_vue();
var slash3 = require_slash();
document.querySelector("#required-vue-version").textContent = version;
document.querySelector("#required-slash3-exists").textContent = !!slash3("foo/bar");
//# sourceMappingURL=@vitejs_test-dep-that-requires.js.map

// -------- node_modules/.vite/deps/chunk-ACQTEB6D.js
import {
  __commonJS
} from "./chunk-PNJKIXPP.js";

// vite:cjs-external-facade:vue
import * as m from "vue";
var require_vue = __commonJS({
  "vite:cjs-external-facade:vue"(exports, module) {
    module.exports = m;
  }
});

export {
  require_vue
};
```

## after

`require('vue')` is failing on browser

```js
import { require_slash_index } from "/node_modules/.vite/deps/slash_index--Dt2Pc4V.js?v=31538b99";

//#region ../../node_modules/.pnpm/@vitejs+test-dep-that-requires@file+playground+external+dep-that-requires_typescript@5.2.2/node_modules/@vitejs/test-dep-that-requires/index.js
const { version } = require('vue');
const slash3 = require_slash_index();
document.querySelector('#required-vue-version').textContent = version;
document.querySelector('#required-slash3-exists').textContent = !!slash3('foo/bar');

//#endregion
//# sourceMappingURL=@vitejs_test-dep-that-requires.js.map
```

</details>

**Comment by hi-ogawa** [comment]
I made separate PRs to fix `playground/external` (https://github.com/rolldown/vite/pull/31) and fix `playground/tsconfig-json` (https://github.com/rolldown/vite/pull/32).

`playground/ssr-noexternal` and `playground/ssr-deps` are fixed in rolldown https://github.com/rolldown/rolldown/issues/1655

For the remaining issues, I made a repro on rolldown repo: `playground/dynamic-import` (https://github.com/rolldown/rolldown/issues/1723) and `playground/alias` (https://github.com/rolldown/rolldown/issues/1722).

I'm closing this PR since the same change is included in other PR.

**Pull request closed without merging**
