### PR TITLE
fix: externalize `optimizeDeps.exclude` via `rolldownCjsExternalPlugin` (fix `test-serve playground/external`)

### PR DESCRIPTION
**Pull request by hi-ogawa**
### Description

Currently `optimizeDeps.exclude` is externalized at the config level `rolldown.rolldown({ external: ... })` and it looks like `rolldownCjsExternalPlugin` doesn't have a chance to fixup cjs external. This manifests as test failures in `playground/external`.

Since `rolldownCjsExternalPlugin` also handles non-cjs external, I simply removed rolldown's `external` config and it looks like tests are passing.

Only the last commit https://github.com/rolldown/vite/pull/31/commits/5edc81d9aaab04b226adc2fbbdf5b017b01ef7cd is the actual fix and first commits are the same one from https://github.com/rolldown/vite/pull/28.

### CODE REVIEW

**Comment by underfin** [comment]
@hi-ogawa I upgrade the lastet rolldown look like the `playground/external` could be work.

**Comment by hi-ogawa** [comment]
I think `playground/external` is still failing (see https://github.com/rolldown/vite/pull/33). I added one commit on top of PR-33 and the test is passing here.

**Comment by hi-ogawa** [comment]
It looks like `CreateModuleContext.resolve_id` https://github.com/rolldown/rolldown/blob/95b15b77340425186148badbee0c2dcf0280c484/crates/rolldown/src/types/module_factory.rs#L30-L51 checks `external` first, then if it matches, it won't call `resolve_id_with_plugins`, so it's necessary to remove `external` config to make it work.

**Comment by underfin** [comment]
Ok.

**Pull request merged**
